Use $JAVA_HOME to find Java binary
flix/vscode-flix pull request #72
Opened 2020-11-05 17:23 UTC by s0kil

I'm using [asdf](https://asdf-vm.com) with https://github.com/halcyon/asdf-java to manage Java versions, however, an error is being thrown due to `ChildProcess.exec` not being able to find Java.

Fixed the issue by using the `bin/java` inside the `$JAVA_HOME` directory.

2020-11-05 18:04 UTC, magnus-madsen commented
@plougsgaard Can you review this? Possible we should use both JAVA_HOME and fall back to some default path (or checking $PATH).

2020-11-05 18:18 UTC, s0kil commented
Maybe a better way to solve this is by setting the shell to `bin/bash` instead of the default `bin/sh` in `ChildProcess.exec`, that way asdf or another tool has a chance to set Java in `$PATH`

2020-11-05 19:16 UTC, s0kil commented
Found a workaround by symbolically linking to `/usr/bin/java`: `sudo ln -s ~/.asdf/shims/java /usr/bin/java`

There could also be an extension config option to set the Java path, this is how many other extensions handle this issue.

2020-11-11 18:41 UTC, plougsgaard requested changes

2020-11-11 18:41 UTC, plougsgaard commented on server/src/engine/flix.ts
> +  // Get JAVA_HOME enviroment variable
enviro**n**ment variable 😄

2020-11-11 18:41 UTC, plougsgaard commented on server/src/engine/flix.ts
> +  if (!javaHome) {
Instead of erroring completely, perhaps we should just fall back to whatever `java` is in `PATH`.

2020-11-11 18:41 UTC, plougsgaard commented on server/src/engine/flix.ts
> +  const javaPath = path.join(javaHome, 'bin', 'java')
As before, check if we can set a path like this, but default to `java`.

2020-11-11 18:41 UTC, plougsgaard commented on server/src/util/javaVersion.ts
> +      if (error) throw error
Why did this line change?

2021-02-01 10:13 UTC, magnus-madsen commented
For now, the solution is to ensure the right Java is on your path.

2021-02-01 10:13 UTC, closed without merging